name: Playwright Automated Tests (SauceDemo project)

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: UI_SauceDemo_tests
        type: choice
        options:
          - UI_SauceDemo_tests

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  download_history:
    runs-on: ubuntu-latest
    name: Download History
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Download Artifact
        run: >
         ARTIFACT_ID=$(curl -L 
         -H "Accept: application/vnd.github+json"
         -H "X-Github-Api-Version: 2022-11-28"
         "https://api.github.com/repos/puncherschance/saucedemo/actions/artifacts?name=allure-results"
         | python -c "import sys, json;print(json.load(sys.stdin)['artifacts'][0]['id'])") 
         &&
         curl -L
         -H "Accept: application/vnd.github+json" 
         -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
         -H "X-GitHub-Api-Version: 2022-11-28" 
         https://api.github.com/repos/puncherschance/saucedemo/actions/artifacts/$ARTIFACT_ID/zip 
         -o artifacts.zip
      - name: Unzip Artifact
        run: >
         mkdir allure-results
         &&
         unzip artifacts.zip -d allure-results
      - name: Store Allure History
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 90
