name: Playwright Automated Tests (SauceDemo project)

on:

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: UI_SauceDemo_tests_with_history
        type: choice
        options:
          - UI_SauceDemo_tests

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  download_history:
    runs-on: ubuntu-latest
    name: Download History
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Download Artifact
        run: >
         ARTIFACT_ID=$(curl -L 
         -H "Accept: application/vnd.github+json"
         -H "X-Github-Api-Version: 2022-11-28"
         "https://api.github.com/repos/puncherschance/saucedemo/actions/artifacts?name=allure-results"
         | python -c "import sys, json;print(json.load(sys.stdin)['artifacts'][0]['id'])") 
         &&
         curl -L
         -H "Accept: application/vnd.github+json" 
         -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
         -H "X-GitHub-Api-Version: 2022-11-28" 
         https://api.github.com/repos/puncherschance/saucedemo/actions/artifacts/$ARTIFACT_ID/zip 
         -o artifacts.zip
         &&
         REPORT_ID=$(curl -L 
         -H "Accept: application/vnd.github+json"
         -H "X-Github-Api-Version: 2022-11-28"
         "https://api.github.com/repos/puncherschance/saucedemo/actions/artifacts?name=github-pages"
         | python -c "import sys, json;print(json.load(sys.stdin)['artifacts'][0]['id'])") 
         &&
         curl -L
         -H "Accept: application/vnd.github+json" 
         -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
         -H "X-GitHub-Api-Version: 2022-11-28" 
         https://api.github.com/repos/puncherschance/saucedemo/actions/artifacts/$REPORT_ID/zip 
         -o pages.zip
      - name: Unzip Artifacts
        run: mkdir allure-results && unzip artifacts.zip -d allure-results
      - name: Unzip Pages
        run: >
         mkdir old_pages pages_history
         &&
         unzip pages.zip -d old_pages
         &&
         tar -xvf old_pages/artifact.tar -C pages_history
      - name: Copy History
        run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results
      - name: Store Allure History
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 90

  UI_SauceDemo_tests:
    runs-on: ubuntu-latest
    needs: download_history
    name: Run UI Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: python -m pip install --upgrade pip 
             pip install -r requirements.txt
      - name: Download Workflow Artifacts
        uses: actions/download-artifact@v3
      - name: Ensure Browsers are Installed
        run: python -m playwright install --with-deps
      - name: Run Tests
        run: pytest --alluredir=allure-results
        continue-on-error: true
      - name: Store Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 90

  generate_allure_report:
    runs-on: ubuntu-latest
    needs: UI_SauceDemo_tests
    name: Generate Allure Report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
      - run: >
         sudo wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
         &&
         sudo tar -zxvf allure-2.29.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
      - name: Download Workflow Artifacts
        uses: actions/download-artifact@v3
      - run: allure generate -c allure-results -o _site
      - name: Store Generated Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path:
            _site
          retention-days: 90

  publish_allure_report:
    runs-on: ubuntu-latest
    needs: generate_allure_report
    name: Publish Allure Report
    steps:
      - name: Download Workflow Artifacts
        uses: actions/download-artifact@v3
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9
